// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";

function Header(Props) {
  return React.createElement("div", {
              className: "teste"
            }, React.createElement(Link, {
                  href: "/",
                  children: React.createElement("a", undefined, "Home")
                }), React.createElement(Link, {
                  href: "/about",
                  children: React.createElement("a", undefined, "About")
                }));
}

var make = Header;

var $$default = Header;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
