// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import '../assets/styles.css';
;

function make(props) {
  var component = props.Component;
  var pageProps = props.pageProps;
  return React.createElement(component, pageProps);
}

var $$default = make;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/*  Not a pure module */
