// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function About(Props) {
  return React.createElement("div", undefined);
}

var make = About;

var $$default = About;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
