// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Index(Props) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Home page!"));
}

var make = Index;

var $$default = Index;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
