// Generated by ReScript, PLEASE EDIT WITH CARE


var Link = {};

var Head = {};

var $$Error = {};

var Router = {};

var GetStaticProps = {};

var GetStaticPaths = {};

export {
  Link ,
  Head ,
  $$Error ,
  Router ,
  GetStaticProps ,
  GetStaticPaths ,
  
}
/* No side effect */
